source "https://rubygems.org"

group :test do
  gem "matest"
end

group :development do
  gem "pry"
  gem "capistrano"
  gem "rake"
end


gem "thin"
# gem "unicorn"

gem "roda"
gem "tilt"
gem "haml"
gem "dotenv"
